name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Docker daemon for insecure registry
        run: |
          echo '{ "insecure-registries" : ["vpn.almaz5200.com:5000"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Build Docker image
        run: docker build -t vpn.almaz5200.com:5000/passport-checker:latest .

      - name: Push Docker image
        run: docker push vpn.almaz5200.com:5000/passport-checker:latest

      - name: Deploy to Debian server
        uses: appleboy/ssh-action@master
        with:
          host: vpn.almaz5200.com
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          env:
            TOKEN: ${{ secrets.TOKEN }}
          script: |
            docker pull vpn.almaz5200.com:5000/passport-checker:latest
            docker stop passport_checker_container || true
            docker rm passport_checker_container || true
            docker run --env TOKEN=$TOKEN -d --name passport_checker_container --restart always -v passport_checker_main_data:/app/data vpn.almaz5200.com:5000/passport-checker:latest
